exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('books').del()
    .then(function () {
      // Inserts sample books
      return knex('books').insert([
        {
          id: '550e8400-e29b-41d4-a716-446655440001',
          title: 'The Somali Language: A Comprehensive Guide',
          title_somali: 'Luuqadda Soomaaliga: Hageyn Buuxa',
          description: 'A comprehensive guide to learning the Somali language, covering grammar, vocabulary, and cultural context.',
          description_somali: 'Hageyn buuxa oo ku saabsan barashada luuqadda Soomaaliga, oo ka kooban qaamuus, erayada, iyo qaab-dhismeedka dhaqanka.',
          author: 'Dr. Ahmed Hassan',
          narrator: 'Amina Mohamed',
          isbn: '978-1-234567-89-0',
          publisher: 'Somali Educational Press',
          publication_year: 2023,
          page_count: 450,
          duration_minutes: 540,
          language: 'bilingual',
          format: 'both',
          genre: 'education',
          age_group: 'all_ages',
          rating: 4.8,
          rating_count: 156,
          cover_image_url: '/covers/somali-language-guide.jpg',
          audio_file_url: '/audio/somali-language-guide.mp3',
          ebook_file_url: '/ebooks/somali-language-guide.epub',
          sample_audio_url: '/samples/somali-language-guide-sample.mp3',
          sample_text_url: '/samples/somali-language-guide-sample.pdf',
          is_featured: true,
          is_new_release: true,
          is_popular: true,
          is_free: false,
          price: 19.99,
          metadata: JSON.stringify({
            difficulty: 'beginner',
            topics: ['grammar', 'vocabulary', 'culture'],
            audioChapters: 15,
            exercises: true
          }),
          tags: JSON.stringify(['somali', 'language', 'education', 'grammar']),
          status: 'published',
          published_at: new Date('2023-01-15')
        },
        {
          id: '550e8400-e29b-41d4-a716-446655440002',
          title: 'Tales from the Horn of Africa',
          title_somali: 'Sheekooyin ka yimid Geeska Afrika',
          description: 'A collection of traditional Somali folktales and stories passed down through generations.',
          description_somali: 'Urur sheekooyin dhaqameed Soomaali ah oo la isku dhaafay jiilka.',
          author: 'Fatima Ali',
          narrator: 'Hassan Abdi',
          isbn: '978-1-234567-89-1',
          publisher: 'Somali Cultural Heritage',
          publication_year: 2022,
          page_count: 280,
          duration_minutes: 320,
          language: 'bilingual',
          format: 'both',
          genre: 'fiction',
          age_group: 'all_ages',
          rating: 4.6,
          rating_count: 89,
          cover_image_url: '/covers/tales-horn-africa.jpg',
          audio_file_url: '/audio/tales-horn-africa.mp3',
          ebook_file_url: '/ebooks/tales-horn-africa.epub',
          sample_audio_url: '/samples/tales-horn-africa-sample.mp3',
          sample_text_url: '/samples/tales-horn-africa-sample.pdf',
          is_featured: true,
          is_new_release: false,
          is_popular: true,
          is_free: true,
          price: 0.00,
          metadata: JSON.stringify({
            storyCount: 25,
            ageRange: '5-12',
            culturalNotes: true,
            illustrations: true
          }),
          tags: JSON.stringify(['folktales', 'culture', 'stories', 'children']),
          status: 'published',
          published_at: new Date('2022-06-20')
        },
        {
          id: '550e8400-e29b-41d4-a716-446655440003',
          title: 'Modern Somali Poetry',
          title_somali: 'Maansooyin Soomaali Cusub',
          description: 'Contemporary Somali poetry exploring themes of love, identity, and social change.',
          description_somali: 'Maansooyin Soomaali cusub oo sahaminaya mawduucyada jacaylka, aqoonsiga, iyo isbedelka bulshada.',
          author: 'Leyla Jama',
          narrator: 'Leyla Jama',
          isbn: '978-1-234567-89-2',
          publisher: 'Somali Arts Foundation',
          publication_year: 2023,
          page_count: 120,
          duration_minutes: 180,
          language: 'somali',
          format: 'both',
          genre: 'poetry',
          age_group: 'adult',
          rating: 4.7,
          rating_count: 67,
          cover_image_url: '/covers/modern-somali-poetry.jpg',
          audio_file_url: '/audio/modern-somali-poetry.mp3',
          ebook_file_url: '/ebooks/modern-somali-poetry.epub',
          sample_audio_url: '/samples/modern-somali-poetry-sample.mp3',
          sample_text_url: '/samples/modern-somali-poetry-sample.pdf',
          is_featured: false,
          is_new_release: true,
          is_popular: false,
          is_free: false,
          price: 12.99,
          metadata: JSON.stringify({
            poemCount: 45,
            themes: ['love', 'identity', 'social change'],
            audioPerformance: true,
            translations: false
          }),
          tags: JSON.stringify(['poetry', 'somali', 'contemporary', 'arts']),
          status: 'published',
          published_at: new Date('2023-03-10')
        },
        {
          id: '550e8400-e29b-41d4-a716-446655440004',
          title: 'Business Success in Somalia',
          title_somali: 'Guulka Ganacsiga Soomaaliya',
          description: 'A practical guide to starting and running successful businesses in Somalia.',
          description_somali: 'Hageyn dhaqsi ah oo ku saabsan bilowga iyo maamulka ganacsiyada guuleysan Soomaaliya.',
          author: 'Mohamed Omar',
          narrator: 'Abdi Rashid',
          isbn: '978-1-234567-89-3',
          publisher: 'Somali Business Institute',
          publication_year: 2022,
          page_count: 320,
          duration_minutes: 420,
          language: 'bilingual',
          format: 'both',
          genre: 'non_fiction',
          age_group: 'adult',
          rating: 4.5,
          rating_count: 134,
          cover_image_url: '/covers/business-success-somalia.jpg',
          audio_file_url: '/audio/business-success-somalia.mp3',
          ebook_file_url: '/ebooks/business-success-somalia.epub',
          sample_audio_url: '/samples/business-success-somalia-sample.mp3',
          sample_text_url: '/samples/business-success-somalia-sample.pdf',
          is_featured: true,
          is_new_release: false,
          is_popular: true,
          is_free: false,
          price: 24.99,
          metadata: JSON.stringify({
            caseStudies: 12,
            businessPlans: 5,
            marketAnalysis: true,
            legalGuidance: true
          }),
          tags: JSON.stringify(['business', 'entrepreneurship', 'somalia', 'economics']),
          status: 'published',
          published_at: new Date('2022-09-15')
        },
        {
          id: '550e8400-e29b-41d4-a716-446655440005',
          title: 'The History of Mogadishu',
          title_somali: 'Taariikhda Muqdisho',
          description: 'A comprehensive history of Mogadishu from ancient times to the present day.',
          description_somali: 'Taariikh buuxa oo ka socda Muqdisho qarniyadii hore ilaa maanta.',
          author: 'Dr. Aisha Mohamed',
          narrator: 'Omar Hassan',
          isbn: '978-1-234567-89-4',
          publisher: 'Somali Historical Society',
          publication_year: 2021,
          page_count: 580,
          duration_minutes: 720,
          language: 'bilingual',
          format: 'both',
          genre: 'history',
          age_group: 'adult',
          rating: 4.9,
          rating_count: 203,
          cover_image_url: '/covers/history-mogadishu.jpg',
          audio_file_url: '/audio/history-mogadishu.mp3',
          ebook_file_url: '/ebooks/history-mogadishu.epub',
          sample_audio_url: '/samples/history-mogadishu-sample.mp3',
          sample_text_url: '/samples/history-mogadishu-sample.pdf',
          is_featured: true,
          is_new_release: false,
          is_popular: true,
          is_free: false,
          price: 29.99,
          metadata: JSON.stringify({
            timePeriod: 'Ancient to Present',
            maps: 15,
            photographs: 50,
            bibliography: true,
            index: true
          }),
          tags: JSON.stringify(['history', 'mogadishu', 'somalia', 'africa']),
          status: 'published',
          published_at: new Date('2021-12-01')
        },
        {
          id: '550e8400-e29b-41d4-a716-446655440006',
          title: 'Somali Cooking Made Easy',
          title_somali: 'Cunista Soomaalida oo Fudud',
          description: 'Learn to cook authentic Somali dishes with easy-to-follow recipes and cooking tips.',
          description_somali: 'Bar cunista cuntooyin Soomaali ah oo dhab ah iyadoo la isticmaalaya recibtada fudud iyo tilmaamaha karinta.',
          author: 'Hodan Ahmed',
          narrator: 'Hodan Ahmed',
          isbn: '978-1-234567-89-5',
          publisher: 'Somali Culinary Arts',
          publication_year: 2023,
          page_count: 240,
          duration_minutes: 300,
          language: 'bilingual',
          format: 'both',
          genre: 'non_fiction',
          age_group: 'all_ages',
          rating: 4.6,
          rating_count: 78,
          cover_image_url: '/covers/somali-cooking-easy.jpg',
          audio_file_url: '/audio/somali-cooking-easy.mp3',
          ebook_file_url: '/ebooks/somali-cooking-easy.epub',
          sample_audio_url: '/samples/somali-cooking-easy-sample.mp3',
          sample_text_url: '/samples/somali-cooking-easy-sample.pdf',
          is_featured: false,
          is_new_release: true,
          is_popular: false,
          is_free: false,
          price: 18.99,
          metadata: JSON.stringify({
            recipeCount: 75,
            difficulty: 'beginner',
            cookingTime: '15-60 minutes',
            ingredients: 'readily available',
            photos: true
          }),
          tags: JSON.stringify(['cooking', 'recipes', 'somali', 'food', 'culinary']),
          status: 'published',
          published_at: new Date('2023-02-28')
        },
        {
          id: '550e8400-e29b-41d4-a716-446655440007',
          title: 'Children\'s Stories from Somalia',
          title_somali: 'Sheekooyin Carruurta Soomaaliya',
          description: 'A delightful collection of children\'s stories featuring animals, adventures, and life lessons.',
          description_somali: 'Urur xiiso leh oo sheekooyin carruur ah oo ka kooban xayawaan, macluumaad, iyo casharada nololka.',
          author: 'Amina Hassan',
          narrator: 'Fatima Ali',
          isbn: '978-1-234567-89-6',
          publisher: 'Somali Children\'s Books',
          publication_year: 2022,
          page_count: 160,
          duration_minutes: 120,
          language: 'bilingual',
          format: 'both',
          genre: 'kids',
          age_group: 'children',
          rating: 4.8,
          rating_count: 92,
          cover_image_url: '/covers/children-stories-somalia.jpg',
          audio_file_url: '/audio/children-stories-somalia.mp3',
          ebook_file_url: '/ebooks/children-stories-somalia.epub',
          sample_audio_url: '/samples/children-stories-somalia-sample.mp3',
          sample_text_url: '/samples/children-stories-somalia-sample.pdf',
          is_featured: true,
          is_new_release: false,
          is_popular: true,
          is_free: true,
          price: 0.00,
          metadata: JSON.stringify({
            storyCount: 20,
            ageRange: '3-8',
            illustrations: true,
            interactive: true,
            moralLessons: true
          }),
          tags: JSON.stringify(['children', 'stories', 'somali', 'education', 'fun']),
          status: 'published',
          published_at: new Date('2022-11-10')
        },
        {
          id: '550e8400-e29b-41d4-a716-446655440008',
          title: 'Islamic Studies in Somali',
          title_somali: 'Cilmiga Islaamka Soomaali',
          description: 'A comprehensive guide to Islamic studies, teachings, and practices in the Somali language.',
          description_somali: 'Hageyn buuxa oo ku saabsan cilmiga Islaamka, macluumaadka, iyo dhaqamada luuqadda Soomaaliga.',
          author: 'Sheikh Abdullahi Mohamed',
          narrator: 'Sheikh Abdullahi Mohamed',
          isbn: '978-1-234567-89-7',
          publisher: 'Somali Islamic Center',
          publication_year: 2022,
          page_count: 400,
          duration_minutes: 600,
          language: 'somali',
          format: 'both',
          genre: 'religion',
          age_group: 'adult',
          rating: 4.7,
          rating_count: 145,
          cover_image_url: '/covers/islamic-studies-somali.jpg',
          audio_file_url: '/audio/islamic-studies-somali.mp3',
          ebook_file_url: '/ebooks/islamic-studies-somali.epub',
          sample_audio_url: '/samples/islamic-studies-somali-sample.mp3',
          sample_text_url: '/samples/islamic-studies-somali-sample.pdf',
          is_featured: true,
          is_new_release: false,
          is_popular: true,
          is_free: false,
          price: 22.99,
          metadata: JSON.stringify({
            topics: ['aqeedah', 'fiqh', 'hadith', 'tafsir'],
            audioLectures: 25,
            references: true,
            glossary: true
          }),
          tags: JSON.stringify(['islam', 'religion', 'somali', 'education', 'spiritual']),
          status: 'published',
          published_at: new Date('2022-07-05')
        }
      ]);
    });
};
