// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAilWZWYgi5vPpymMPJpvCZnW63Nz1wawQ',
    appId: '1:4861039733:web:YOUR_ACTUAL_WEB_APP_ID', // ← Replace with your actual web app ID
    messagingSenderId: '4861039733',
    projectId: 'teekoob',
    authDomain: 'teekoob.firebaseapp.com',
    storageBucket: 'teekoob.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAilWZWYgi5vPpymMPJpvCZnW63Nz1wawQ',
    appId: '1:4861039733:android:a4c2a00b30ea81d006543c',
    messagingSenderId: '4861039733',
    projectId: 'teekoob',
    storageBucket: 'teekoob.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAilWZWYgi5vPpymMPJpvCZnW63Nz1wawQ',
    appId: '1:4861039733:ios:a4c2a00b30ea81d006543c',
    messagingSenderId: '4861039733',
    projectId: 'teekoob',
    storageBucket: 'teekoob.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAilWZWYgi5vPpymMPJpvCZnW63Nz1wawQ',
    appId: '1:4861039733:ios:your_macos_app_id',
    messagingSenderId: '4861039733',
    projectId: 'teekoob',
    storageBucket: 'teekoob.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAilWZWYgi5vPpymMPJpvCZnW63Nz1wawQ',
    appId: '1:4861039733:web:your_windows_app_id',
    messagingSenderId: '4861039733',
    projectId: 'teekoob',
    authDomain: 'teekoob.firebaseapp.com',
    storageBucket: 'teekoob.firebasestorage.app',
  );
}
